### ISSUE TITLE
Commands with arrow

### ISSUE THREAD

**Issue by geomtech** [Alve-OS/Alve-Operating-System#13]
Access to previous command used with arrows on keyboard.

**Comment by valentinbreiz** [comment]
We should save the last commands into a list<>

**Comment by geomtech** [comment]
Yeah I thinked to do that, I think I will make this today. Add all commands typed into a list and to back with an id etc..

**Comment by valentinbreiz** [comment]
It's not an issue, but it need to be implemented I update the TODO.md file.
